version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
      - "5006:5006"
    environment:
      - ConnectionStrings__PostgreSqlConnection=Host=db;Database=DB_FIAP_ARQUITETO;Username=postgres;Password=Teste@123
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: DB_FIAP_ARQUITETO
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Teste@123
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/FiapDB.SQL:/docker-entrypoint-initdb.d/FiapDB.sql
